image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r requirements-test.txt
      pip install -e .
vscode:
  extensions:
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - hbenl.vscode-test-explorer
    - editorconfig.editorconfig
